version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_db_galileo_tarea4
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser_tarea4
      POSTGRES_PASSWORD: galileO_2025
      POSTGRES_DB: bdd_galileo_tarea4
    ports:
      - "65432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

